### ISSUE TITLE
client.get_by_activity() returns 0 torrents

### ISSUE THREAD

**Issue by mesterhazi** [radaron/ncoreparser#7]
I checked the raw HTTP answer and it looks like there is an extra space so the regex won't find the pattern:
e.g.: <a  href="torrents.php?action=details&id=2213705"
This can be fixed by changing the regexp to this: r'<a  href=".*?" onclick="torrent\((.*?)\); return false;'

**Comment by radaron** [comment]
Thank you for the catch. I will fix it soon.

**Comment by radaron** [comment]
I guess it happened because the html page was changed. In the latest release the tests/manual.py worked as expected. I think the ncore staff started refactoring their codes.
